### ISSUE TITLE
Not creating database

### ISSUE THREAD

**Issue by xereeto** [JoinRaven/Raven#10]
Started rethinkdb normally, it appears to connect to it but this error message is produced after several minutes:
Unhandled rejection ReqlOpFailedError: Database `raven` does not exist in:
r.table("leaderElection").insert({

**Comment by wgoodall01** [comment]
Are all the required tables set up in rethinkdb? Open a node shell in the root of the project, and type the following:
```
require("./lib/db").setup().then(()=>{console.log("Done")})
```

**Comment by Sxw1212** [comment]
Fixed in latest version.
