### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheDarocker** [JoinRaven/Raven#18]
What license is Raven and it's code being published under? [Here's a page to help out with that choice.](http://choosealicense.com/)

**Comment by Sxw1212** [comment]
ISC, as shown in package.json. I'll make this more clear.

**Comment by TheDarocker** [comment]
Just throw in a LICENSE.md or somethin

**Comment by Sxw1212** [comment]
Added in 6fdfeb284993769b9c4903cabfc4c3ca76ba2243
